language: minimal

jobs:
    include:
        - script: 
            - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            - docker build ./udagram-service-feed -t crdominguez/udagram-service-feed
            - docker push crdominguez/udagram-service-feed
        - script: 
            - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            - docker build ./udagram-service-user -t crdominguez/udagram-service-user
            - docker push crdominguez/udagram-service-user
        - script: 
            - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            - docker build ./udagram-frontend -t crdominguez/udagram-frontend
            - docker push crdominguez/udagram-frontend
        - script: 
            - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            - docker build ./nginx -t crdominguez/udagram-nginx
            - docker push crdominguez/udagram-nginx