apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-service-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-service-user
  template:
    metadata:
      labels:
        app: udagram-service-user
    spec:
      containers:
      - name: udagram-service-user
        image: crdominguez/udagram-service-user
        resources:
          requests:
            cpu: 0.1
        envFrom:
          - secretRef:
              name: udagram-secrets
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: udagram-service-user
spec:
  selector:
    app: udagram-service-user
  ports:
  - port: 8080
    targetPort: 8080