apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend
spec:
  selector:
    matchLabels:
      app: udagram-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: udagram-frontend
    spec:
      containers:
      - name: udagram-frontend
        image: crdominguez/udagram-frontend
        envFrom:
          - secretRef:
              name: udagram-secrets
        ports:
        - containerPort: 8100
---
apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend
spec:
  selector:
    app: udagram-frontend
  ports:
  - port: 8100
    targetPort: 8100